stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - echo "Build complete!"

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests complete!"
